version: "3"
services:
  web_api:
    image: web_api
    container_name: web_api_application
    build:
      context: ./WebApi
      dockerfile: Dockerfile
    ports:
      - "5000:80"
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=123
  angular_client:
    build:
      context: ./AngularClient
      dockerfile: Dockerfile
    image: angular_client
    container_name: angular_client
    ports:
      - "6969:80"
